# Custom Language File for Launcher Customizer

[ejs.app]
title = "MekaMiners Brasil - Launcher"

[ejs.landing]
mediaDiscordURL = "https://discord.gg/BPYSP5YsaY"
mediaYoutubeURL = "https://www.youtube.com/@EuSouMercy"

[ejs.settings]
sourceGithubLink = ""
supportLink = "https://discord.gg/BPYSP5YsaY"

[ejs.welcome]
welcomeHeader = "BEM-VINDOS AO MEKAMINERS BRASIL"
welcomeDescription = ""
welcomeDescCTA = "Você está a apenas alguns cliques do melhor servidor de mods do Brasil."
